application: emdec-gtransit
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "1s"

handlers:

- url: /(css|images|js)/(.*)
  static_files: static/\1/\2
  upload: static/(css|images|js|translation|papers)/(.*)

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "latest"
- name: webob
  version: "latest"
- name: markupsafe
  version: "latest"
- name: setuptools
  version: "latest"
- name: jinja2
  version: "latest"
- name: lxml
  version: "latest"
- name: ssl
  version: latest
