application: emdec-gtransit
version: 1
runtime: python27
api_version: 1
threadsafe: yes
instance_class: F2

default_expiration: "1s"

handlers:
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "latest"
- name: webob
  version: "latest"
- name: markupsafe
  version: "latest"
- name: setuptools
  version: "latest"
- name: jinja2
  version: "latest"
- name: lxml
  version: "latest"
- name: ssl
  version: latest
